// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use crate::types::*;
use diesel::serialize::ToSql;
use diesel::deserialize::FromSql;
use diesel::sql_types::Jsonb;
use diesel::AsExpression;
use serde_json::Value as JsonValue;
use serde::{ Deserialize, Serialize };

use diesel::prelude::*;
#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Selectable, Insertable, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = architecture)]
pub struct Architecture {
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Selectable, Insertable, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = operating_system)]
pub struct OperatingSystem {
    pub id: i32,
    pub name: String,
    pub version: String,
    pub system_type: OsType,
    pub release: String,
    pub architecture: i32,
    pub summary: String,
    pub url: String,
    pub license: String,
    pub description: String,
    pub manager: i32,
    pub distro_tag: Option<String>,
}

#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Selectable, Insertable, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = operating_system_package)]
pub struct OperatingSystemPackage {
    pub id: i32,
    pub id_os: Option<i32>,
    pub id_package: Option<i32>,
}

#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Selectable, Insertable, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = package)]
pub struct Package {
    pub id: i32,
    pub name: String,
    pub version: String,
    pub release: String,
    pub architecture: i32,
    pub package_size: String,
    pub source: String,
    pub repository: String,
    pub summary: String,
    pub url: String,
    pub license: String,
    pub description: String,
    pub in_repo: Option<bool>,
    pub created: Option<bool>,
    pub vulnerable: Option<bool>,
}

#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Selectable, Insertable, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = package_dependencies)]
pub struct PackageDependency {
    pub id: i32,
    pub id_package: Option<i32>,
    pub id_dependency: Option<i32>,
}

#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Selectable, Insertable, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = package_manager)]
pub struct PackageManager {
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Selectable, Insertable, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = product)]
pub struct Product {
    pub id: i32,
    pub id_os: i32,
    pub format: OsFormat,
}

