[package]
name = "pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive", "env", "wrap_help"] }
dagger-sdk = "0.18.12"
diesel = { version = "~2.2.11", features = ["postgres", "r2d2", "uuid", "chrono", "serde_json"] }
eyre = "~0.6.12"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "~1.46.0"
